name: 'Rebol-Easing CI'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.7.1

    - name: Build 32bit Rebol/Easing extension
      run: ./siskin Rebol-Easing.nest --msvc easing-windows-x86

    - name: Prepare 32bit Rebol/Easing extension
      run:  MOVE ./msvc/Release-Win32/easing-windows-x86.dll ./easing-windows-x86.rebx

    - name: Build 64bit Rebol/Easing extension
      run: ./siskin Rebol-Easing.nest --msvc easing-windows-x64

    - name: Prepare 64bit Rebol/Easing extension
      run:  MOVE ./msvc/Release-x64/easing-windows-x64.dll ./easing-windows-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0

    - name: Minimal Rebol/Easing extension test
      run:  ./rebol3 ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-Easing-CI-windows-${{github.run_id}}
        path: ./easing*.rebx

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.7.1

    - name: Build 64bit Rebol/Easing extension
      run: ./siskin Rebol-Easing.nest --clean easing-linux-x64

    - name: Prepare 64bit Rebol Easing extension
      run:  mv ./build/easing-linux-x64.so ./easing-linux-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0

    - name: Minimal Rebol/Easing extension test
      run:  ./rebol3 ci-test.r3

    - name: Compress 64bit Rebol/Easing extension
      run:  gzip -9 ./easing-linux-x64.rebx

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-Easing-CI-linux-${{github.run_id}}
        path: ./easing*.gz

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.7.1

    - name: Build 64bit Rebol/Easing extension
      run: ./siskin Rebol-Easing.nest --clean easing-macos-x64

    - name: Prepare 64bit Rebol Easing extension
      run:  mv ./build/easing-macos-x64.dylib ./easing-macos-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0

    - name: Minimal Rebol/Easing extension test
      run:  ./rebol3 ci-test.r3

    - name: Compress 64bit Rebol/Easing extension
      run:  gzip -9 ./easing-macos-x64.rebx

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-Easing-CI-macos-${{github.run_id}}
        path: ./easing*.gz

